# Generated by Django 6.0.7 on 2026-08-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('hex_cor', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
    ]
